[phases.setup]
nixPkgs = ['nodejs', 'nodePackages.pnpm']

[phases.install]
cmds = [
  "pnpm install"
]

[phases.build]
cmds = [
  "cd backend && pnpm install && pnpm build"
]

[start]
cmd = "cd backend && node dist/index.js"
