[build]
install = "npm i -g pnpm && pnpm i --frozen-lockfile"
command = "pnpm --filter backend exec prisma generate && pnpm --filter backend build"

[start]
command = "pnpm --filter backend exec prisma migrate deploy && pnpm --filter backend start"
