[build]
install = "npm i -g pnpm"
command = "pnpm install && cd backend && pnpm install && pnpm exec prisma generate && pnpm run build"

[start]
command = "cd backend && pnpm exec prisma migrate deploy && pnpm start"
