############################################################
# Monorepo Railway config: backend + frontend services
############################################################

[services.backend]
root = "backend"
build = "npm i -g pnpm && pnpm install --no-frozen-lockfile && pnpm prisma generate && pnpm build"
start = "npm run prisma:migrate && npm start"

[services.frontend]
root = "frontend"
build = "npm i -g pnpm && pnpm install --no-frozen-lockfile && pnpm build"
start = "npm run preview -- --host 0.0.0.0 --port ${PORT:-8080}"
