[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "cd backend && node dist/index.js"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"

[service]
autoDeploy = true
