[build]
builder = "nixpacks"
buildCommand = "npm i -g pnpm && cd backend && pnpm install --no-frozen-lockfile && pnpm exec prisma generate && pnpm run build"

[deploy]
startCommand = "cd backend && pnpm exec prisma migrate deploy && pnpm start"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 100
